# Generated by Django 5.2.7 on 2025-10-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('script_file', models.FileField(upload_to='scripts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
