# Generated by Django 5.2.7 on 2025-10-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationscript',
            name='category',
            field=models.CharField(choices=[('data', 'Data Processing'), ('excel', 'Excel Migration'), ('sentiment', 'Sentiment Analysis'), ('sql', 'SQL Tools'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=50),
        ),
    ]
