# Generated by Django 5.1 on 2026-04-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_automationscript_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationscript',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='The Gourmet Story/Recipe documentation'),
        ),
        migrations.AddField(
            model_name='automationscript',
            name='environment_target',
            field=models.CharField(choices=[('sb', 'StackBlitz (Light)'), ('cs', 'Codespaces (Standard)'), ('rp', 'Replit (Heavy)'), ('lr', 'Local Recommended')], default='sb', max_length=2),
        ),
        migrations.AddField(
            model_name='automationscript',
            name='has_sample_data',
            field=models.BooleanField(default=False, help_text='Can be run with pre-bundled sample files'),
        ),
        migrations.AddField(
            model_name='automationscript',
            name='release_url',
            field=models.URLField(blank=True, help_text='Link to latest release download'),
        ),
        migrations.AddField(
            model_name='automationscript',
            name='repo_url',
            field=models.URLField(blank=True, help_text='Link to GitHub repository'),
        ),
        migrations.AddField(
            model_name='automationscript',
            name='security_disclaimer',
            field=models.TextField(blank=True, help_text='Specific security concerns for this script'),
        ),
        migrations.AddField(
            model_name='automationscript',
            name='security_level',
            field=models.CharField(choices=[('low', 'Low-Impact (Utility)'), ('high', 'High-Access (System)'), ('exp', 'Experimental')], default='low', max_length=4),
        ),
        migrations.AlterField(
            model_name='automationscript',
            name='category',
            field=models.CharField(choices=[('data', 'Data Processing'), ('nlp', 'Natural Language'), ('web', 'Web Automation'), ('sql', 'SQL Tools'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=50),
        ),
    ]
